# Generated by Django 4.0.5 on 2022-06-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_customer_menu_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='pizza_image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
