# Generated by Django 4.0.5 on 2022-06-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0010_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='PENDING', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
                ('total_price', models.CharField(max_length=50)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.customer')),
            ],
        ),
    ]
