# Generated by Django 4.0.5 on 2022-06-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0012_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
