# Generated by Django 4.0.5 on 2022-07-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0013_alter_mycart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
